"""Render the wiki's document catalog and experiment table; never infer findings."""
import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ("roadmap/artifacts.md", "roadmap/experiments.md")


def markdown_files():
    """Use the checkout's tracked and nonignored files, never sibling worktrees."""
    output = subprocess.check_output(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        cwd=ROOT,
    ).decode()
    paths = {
        p for p in output.split("\0")
        if p.endswith(".md") and not p.startswith(("worktrees/", ".venv/", "node_modules/"))
        and (ROOT / p).is_file()
    }
    return sorted(paths | set(OUTPUTS))


def cell(value):
    """Escape supplied text for a Markdown table without changing its meaning."""
    return str(value).replace("|", "\\|").replace("\n", " ")


def render():
    """Validate declared records and return deterministic reading projections."""
    data = json.loads((ROOT / "roadmap/experiments.json").read_text(encoding="utf-8"))
    records = data["experiments"]
    families = data["families"]
    if not isinstance(families, list) or not families or any(
        not isinstance(family, str) or not re.fullmatch(r"[a-z]+(?:-[a-z]+)*", family)
        for family in families
    ):
        raise ValueError("Families must be a nonempty list of lowercase slug names")
    if len(set(families)) != len(families):
        raise ValueError("Duplicate declared experiment family")
    by_family = {family: [] for family in families}
    ids, coverage = set(), {}
    for record in records:
        ident = record["id"]
        if ident in ids:
            raise ValueError(f"Duplicate experiment ID: {ident}")
        ids.add(ident)
        if record["review_status"] not in {"result_reviewed", "not_reviewed"}:
            raise ValueError(f"Unknown review status: {ident}")
        if record["review_status"] == "not_reviewed" and record.get("outcome") is not None:
            raise ValueError(f"Unreviewed record must not assert an outcome: {ident}")
        if record["family"] not in by_family:
            raise ValueError(f"Undeclared experiment family: {ident}: {record['family']}")
        by_family[record["family"]].append(record)
        for path in record["artifacts"]:
            target = (ROOT / path).resolve()
            if not target.is_relative_to(ROOT) or not target.exists():
                raise ValueError(f"Missing or out-of-scope artifact: {ident}: {path}")
            if path in coverage:
                raise ValueError(f"Artifact assigned twice: {path}")
            coverage[path] = ident
    paths = markdown_files()
    missing = [p for p in paths if p.startswith("goal-discovery/docs/hypotheses/") and p not in coverage]
    if missing:
        raise ValueError(f"Hypothesis artifacts missing from register: {missing}")

    catalog = [
        "# Complete document catalog",
        "",
        "<!-- GENERATED by scripts/render_knowledge_index.py; do not edit. -->",
        "",
        "[Wiki](README.md) · [Research synthesis](research.md) · [Experiment register](experiments.md)",
        "",
        "Find a document here; use the topic synthesis for its significance. Classification",
        "below is location-based navigation, not a scientific verdict or lifecycle decision.",
        "Historical evidence remains available without becoming current instructions.",
        "",
    ]
    groups = {}
    for path in paths:
        group = "Project entrypoints" if "/" not in path else str(Path(path).parent)
        groups.setdefault(group, []).append(path)
    for group, items in sorted(groups.items()):
        catalog.extend([f"## {group}", ""])
        catalog.extend(f"- [{Path(p).name}](../{p})" for p in items)
        catalog.append("")

    table = [
        "# Experiment register",
        "",
        "<!-- GENERATED from experiments.json by scripts/render_knowledge_index.py; do not edit. -->",
        "",
        "[Wiki](README.md) · [Research synthesis](research.md) · [Canonical records](experiments.json)",
        "",
        "One record may link several protocols/results. Reviewed means a documentation",
        "review of cited results, not a new execution or confirmation. Unreviewed records",
        "carry no inferred scientific outcome. Costs remain unknown unless measured.",
        "",
        (
            f"**{len(records)} records: "
            f"{sum(r['review_status'] == 'result_reviewed' for r in records)} reviewed; "
            f"{sum(r['review_status'] == 'not_reviewed' for r in records)} unreviewed.**"
        ),
        "",
        "Browse by declared family. Counts describe documentation review coverage,",
        "not scientific success or progress; historical dispositions are not current assignments.",
        "",
        "| Family | Records | Reviewed | Unreviewed |",
        "|---|---:|---:|---:|",
    ]
    for family, items in by_family.items():
        reviewed = sum(r["review_status"] == "result_reviewed" for r in items)
        table.append(
            f"| [{family}](#{family}) | {len(items)} | {reviewed} | {len(items) - reviewed} |"
        )
    for family, items in by_family.items():
        table.extend([
            "", f"## {family}", "",
            "| Experiment | Question | Review | Outcome / disposition | Native evidence |",
            "|---|---|---|---|---|",
        ])
        for r in items:
            refs = "; ".join(f"[{Path(p).stem}](../{p})" for p in r["artifacts"])
            result = r.get("outcome") or "Not assessed"
            disposition = r.get("disposition") or "Review before use"
            table.append(
                f"| {cell(r['id'])} | {cell(r['question'])} | "
                f"{cell(r['review_status'])} | {cell(result)}; {cell(disposition)} | {refs} |"
            )
    table.extend(["", "Interpretation and counterevidence live in the linked research synthesis and native results.", ""])
    return {OUTPUTS[0]: "\n".join(catalog), OUTPUTS[1]: "\n".join(table)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rendered = render()
    except (ValueError, KeyError, TypeError, OSError) as error:
        print(f"FAIL: {error}")
        return 1
    stale = []
    for path, content in rendered.items():
        target = ROOT / path
        if args.write:
            target.write_text(content, encoding="utf-8")
        elif not target.exists() or target.read_text(encoding="utf-8") != content:
            stale.append(path)
    if stale:
        print("FAIL: stale projections: " + ", ".join(stale))
        return 1
    print("PASS: document catalog, experiment coverage, IDs, paths, and projections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
