#!/usr/bin/env node
import {createServer} from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';import process from 'node:process';import {chromium} from 'playwright';
const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..'),PORT=Number(process.env.HYPERGRAPH_SMOKE_PORT||4177),VIEWER='/wiki/reference/metamodel/hypergraph-viewer.html',ART=path.join(ROOT,'artifacts'),SHOT=path.join(ART,'scientific-hypergraph-viewer.png');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.jsonld':'application/ld+json; charset=utf-8'};
const safe=u=>{const p=decodeURIComponent(new URL(u,`http://127.0.0.1:${PORT}`).pathname),r=path.resolve(ROOT,`.${p}`);return r.startsWith(ROOT+path.sep)||r===ROOT?r:null};
async function serve(req,res){const f=safe(req.url||'/');if(!f||!existsSync(f)){res.writeHead(404);return res.end('not found')}try{res.writeHead(200,{'content-type':MIME[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});res.end(await readFile(f))}catch(e){res.writeHead(500);res.end(String(e))}}
function assert(c,m){if(!c)throw Error(m)}async function wait(page,fn,t=15000){await page.waitForFunction(fn,null,{timeout:t});await page.waitForTimeout(100)}
const server=createServer((a,b)=>void serve(a,b));await new Promise(r=>server.listen(PORT,'127.0.0.1',r));const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1800,height:1200}}),errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.stack||String(e)));
try{
 await page.goto(`http://127.0.0.1:${PORT}${VIEWER}`,{waitUntil:'domcontentloaded'});
 try{await wait(page,()=>/semantic hub/.test(document.querySelector('#status')?.textContent||''));}catch(error){await mkdir(ART,{recursive:true});await page.screenshot({path:SHOT,fullPage:true});console.error('VIEWER STATUS:',await page.locator('#status').textContent());console.error('BROWSER ERRORS:',errors.join('\n'));throw error;}
 const initial=await page.evaluate(()=>{const ids=[...document.querySelectorAll('#viewport .node,#viewport .relation')].map(x=>x.dataset.id).filter(Boolean);return{status:document.querySelector('#status')?.textContent||'',ids,nodes:document.querySelectorAll('#viewport .node').length,relations:document.querySelectorAll('#viewport .relation').length,domains:document.querySelectorAll('#viewport .domain-label').length}});
 await mkdir(ART,{recursive:true});await page.screenshot({path:SHOT,fullPage:true});
 assert(initial.nodes>0&&initial.relations>0,'graph did not render');assert(initial.domains>=4,`expected >=4 domain labels; got ${initial.domains}`);assert(new Set(initial.ids).size===initial.ids.length,'rendered IDs are not unique');assert(initial.ids.includes('mechanics::study:LabFrame')&&initial.ids.includes('oscillator::study:LabFrame'),'fixture-local LabFrame identities collapsed');
 const overlap=await page.evaluate(()=>{const xs=[...document.querySelectorAll('#viewport .node-shape,#viewport .relation-shape')].map(e=>({id:e.parentElement?.dataset.id,r:e.getBoundingClientRect()})).filter(x=>x.id);let severe=0,significant=0,worst=0,pair=null;for(let i=0;i<xs.length;i++)for(let j=i+1;j<xs.length;j++){const a=xs[i].r,b=xs[j].r,ix=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left)),iy=Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)),area=ix*iy;if(!area)continue;const ratio=area/(Math.min(a.width*a.height,b.width*b.height)||1);if(ratio>.08)significant++;if(ratio>.35)severe++;if(ratio>worst){worst=ratio;pair=[xs[i].id,xs[j].id]}}return{count:xs.length,significant,severe,worst,pair}});
 assert(overlap.severe===0,`severe hub collisions: ${JSON.stringify(overlap)}`);
 await page.locator('#viewport .relation').first().click();assert(await page.locator('#roles .role').count()>=2,'relation inspector missing roles');
 const before=await page.locator('#viewport .node,#viewport .relation').count();await page.locator('#focus').click();await wait(page,()=>/semantic hub/.test(document.querySelector('#status')?.textContent||''));const after=await page.locator('#viewport .node,#viewport .relation').count();assert(after>0&&after<before,`focus did not reduce graph ${before}->${after}`);await page.locator('#focus').click();await wait(page,()=>/semantic hub/.test(document.querySelector('#status')?.textContent||''));
 await page.locator('#search').fill('velocity');assert(await page.locator('#viewport .dim').count()>0,'search did not dim nonmatches');await page.locator('#search').fill('');assert(errors.length===0,`browser errors: ${errors.join('\n')}`);
 console.log(`PASS exact hub viewer: ${initial.status}`);console.log(`PASS ${initial.nodes} elements + ${initial.relations} hyperrelations across ${initial.domains} domain lobes`);console.log(`PASS shape overlap significant=${overlap.significant} severe=${overlap.severe} worst=${(overlap.worst*100).toFixed(1)}%`);console.log(`PASS identity isolation, inspector, focus ${before}->${after}, search, console`);console.log(`SCREENSHOT ${path.relative(ROOT,SHOT)}`);
}finally{await browser.close();server.close()}
